version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: recommendation-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: recommendation_platform
      MYSQL_USER: recommendation_user
      MYSQL_PASSWORD: recommendation_pass
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./recommendation-common/src/main/resources/db/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone='+08:00'
      --max_connections=1000
      --innodb_buffer_pool_size=256M
      --innodb_log_file_size=128M
      --innodb_flush_log_at_trx_commit=2
      --innodb_flush_method=O_DIRECT
      --slow_query_log=1
      --slow_query_log_file=/var/lib/mysql/slow.log
      --long_query_time=2
    networks:
      - recommendation-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: recommendation-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - recommendation-network

  # Elasticsearch搜索引擎
  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: recommendation-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - recommendation-network

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: recommendation-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - recommendation-network

  # ClickHouse分析数据库
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: recommendation-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: recommendation_analytics
      CLICKHOUSE_USER: analytics_user
      CLICKHOUSE_PASSWORD: analytics_pass
    networks:
      - recommendation-network

  # 特征服务
  feature-service:
    build: ./feature-service
    container_name: recommendation-feature-service
    restart: unless-stopped
    ports:
      - "8003:8003"
    environment:
      - HOST=0.0.0.0
      - PORT=8003
      - DEBUG=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DATABASE=recommendation
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin123
      - USER_FEATURE_EXPIRE=3600
      - CONTENT_FEATURE_EXPIRE=7200
      - BATCH_SIZE=1000
      - LOG_LEVEL=INFO
    volumes:
      - ./feature-service/logs:/app/logs
    depends_on:
      - redis
      - clickhouse
      - rabbitmq
    networks:
      - recommendation-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  rabbitmq_data:
    driver: local
  clickhouse_data:
    driver: local

networks:
  recommendation-network:
    driver: bridge