# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "recommendation_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # 推荐服务监控
  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # 用户服务监控
  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # 内容服务监控
  - job_name: 'content-service'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # 数据收集服务监控
  - job_name: 'data-collection-service'
    static_configs:
      - targets: ['localhost:8083']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 特征服务监控
  - job_name: 'feature-service'
    static_configs:
      - targets: ['localhost:8084']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 排序服务监控
  - job_name: 'ranking-service'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # MySQL监控
  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']
    scrape_interval: 30s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s

  # Elasticsearch监控
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['localhost:9114']
    scrape_interval: 30s

  # RabbitMQ监控
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['localhost:15692']
    scrape_interval: 30s

  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s