# 数据库配置文件
# 包含MySQL连接配置和连接池设置

spring:
  datasource:
    # MySQL数据库连接配置
    url: jdbc:mysql://localhost:3306/recommendation_platform?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:recommendation_user}
    password: ${DB_PASSWORD:recommendation_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # HikariCP连接池配置
    hikari:
      # 连接池大小配置
      maximum-pool-size: 20          # 最大连接数
      minimum-idle: 5                # 最小空闲连接数
      
      # 连接超时配置(毫秒)
      connection-timeout: 30000      # 连接超时时间
      idle-timeout: 600000           # 空闲连接超时时间(10分钟)
      max-lifetime: 1800000          # 连接最大生存时间(30分钟)
      leak-detection-threshold: 60000 # 连接泄漏检测阈值(1分钟)
      
      # 连接池名称
      pool-name: RecommendationHikariCP
      
      # 连接测试
      connection-test-query: SELECT 1
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate              # 验证数据库表结构，不自动创建
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
    # 显示SQL语句(开发环境)
    show-sql: false
    
    properties:
      hibernate:
        # SQL格式化
        format_sql: true
        # 批量操作配置
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        # 二级缓存配置
        cache:
          use_second_level_cache: false
          use_query_cache: false
        # 统计信息
        generate_statistics: false

  # Flyway数据库迁移配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    encoding: UTF-8
    table: flyway_schema_history

# 数据库连接池监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,hikaricp
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    com.zaxxer.hikari: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE