# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'recommendation-api-gateway'
    environment: 'production'

# 告警规则文件
rule_files:
  - "rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Kong网关监控
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # 推荐服务监控
  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:8080']
    scrape_interval: 15s
    metrics_path: /actuator/prometheus
    scrape_timeout: 10s

  # 用户服务监控
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    scrape_interval: 15s
    metrics_path: /actuator/prometheus
    scrape_timeout: 10s

  # 内容服务监控
  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:8082']
    scrape_interval: 15s
    metrics_path: /actuator/prometheus
    scrape_timeout: 10s

  # 特征服务监控
  - job_name: 'feature-service'
    static_configs:
      - targets: ['feature-service:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # 数据库监控
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch监控
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s
    metrics_path: /metrics

  # ClickHouse监控
  - job_name: 'clickhouse-exporter'
    static_configs:
      - targets: ['clickhouse-exporter:9116']
    scrape_interval: 30s
    metrics_path: /metrics

# 远程写入配置（可选）
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置（可选）
# remote_read:
#   - url: "http://remote-storage:9201/read"